### ISSUE TITLE
Kommerzielle Nutzung

### ISSUE THREAD

**Issue by Lordcybertracker** [matthias-bs/BresserWeatherSensorTTN#11]
Hallo,
Darf man das Projekt bei Kommerziellen allerdings nicht Gewinnbringenden Projekten Nutzen?
Projekt siehe: hsn-ttn.de
Danke

**Comment by matthias-bs** [comment]
Hallo, 
Ja, das lässt die gewählte [MIT-Lizenz](https://github.com/matthias-bs/BresserWeatherSensorTTN/blob/main/LICENSE) ausdrücklich zu.
Viele Grüße
Matthias

**Comment by matthias-bs** [comment]
Ich würde mich über Infos freuen, ob/wie mein Projekt eingesetzt wird!

**Comment by Lordcybertracker** [comment]
Danke werd  ich tun. Melden sie /Du sich am besten unter info@hsn-ttn.de
Danke
