### ISSUE TITLE
LoraData too long

### ISSUE THREAD

**Issue by DL4AAS** [matthias-bs/BresserWeatherSensorTTN#18]
Hi,

if some sensors are not available and commented out, the data sent to LoRaWAN is too long.

The reason is obvious:
    // Schedule transmission
    if (! myLoRaWAN.SendBuffer(
        loraData, sizeof(loraData), ...

Change sizeof(loraData) to encoder.getLength() should give a better result.

Regards,
Jens

**Comment by matthias-bs** [comment]
Hi,

absolutely! I introduced this a while ago, but accidentally overwrote it (0c32fbc17d6068ed13020dd9cc7e7bfbfe4beaf4).

Fixed in 855d50fec896e22fc19a2b6a13e2f7e76dcac4ab.

Thanks for reporting!

Best regards,
Matthias

**Comment by matthias-bs** [comment]
Hi,

can this issue be closed?

Best regards
Matthias

**Comment by DL4AAS** [comment]
Hi Matthias,

Yes, thanks.

The rain counter User Byte 12, as YouTube thought. Byte 16 is different,
but I have only one type of sensor..

Jens

Matthias Prinke ***@***.***> schrieb am Do., 5. Jan. 2023,
10:27:
