### ISSUE TITLE
Wrong author in references

### ISSUE THREAD

**Issue by koenvervloesem** [matthias-bs/BresserWeatherSensorTTN#48]
Hi, I'm not the author of Theengs Decoder, as is now shown in the references, but just a minor contributor. Maybe change the author to "the Theengs project"?

**Comment by matthias-bs** [comment]
Hi,
o.k., changed in https://github.com/matthias-bs/BresserWeatherSensorTTN/commit/94fa93b7113e92c5e6f9cf4f9ad88065113423b4. Anyway, thanks you for your contribution!
Best regards
Matthias

**Comment by koenvervloesem** [comment]
Thanks! And keep up with your great project!
