### ISSUE TITLE
request for adding heltec-wifi-lora-32-v3 as supported board

### ISSUE THREAD

**Issue by evon800c** [matthias-bs/BresserWeatherSensorTTN#80]
Hi Matthias,
​you know from other experiences with me, I'm not an expert in that world.
What do you think about adding the heltec-wifi-lora-32-v3 card as a supported card too?
You can use me, my board and my weather station as testers, :-) .
Let me know.
Many thanks for your time. Davide

**Comment by matthias-bs** [comment]
Hi Davide,

I'd really like to do that, but unfortunately the SX1262 is not supported by the underlying [arduino-lmic](https://github.com/mcci-catena/arduino-lmic) and - even worse - development of arduino-lmic seems to have stopped.

The SX1262's LoRaWAN part seems to be quite different from the SX1276's, so this would not be trivial and the arduino-lmic code is not easy to maintain.

Maybe it is more fruitful to keep an eye on the LoraWAN implementation in [RadioLib](https://github.com/jgromes/RadioLib) than to spend efforts in arduino-lmic.

So, in the near future, you will have to use a different board.

Cheers,
Matthias
